<?php
    //The "vendor" folder typically contains third-party libraries and dependencies that your PHP project relies on. These dependencies are often managed using a package manager like Composer.
    //The "vendor/autoload.php" file, generated by Composer, is an important file located within this directory. It provides autoloading for all the installed packages, ensuring that you can use classes and functions from these packages in your code without explicitly including or requiring each file.
    //The "bin" folder, short for "binary," is where you typically place executable scripts or command-line tools associated with your project.

    //Package: PHPUnit
    //Install: composer require phpunit/phpunit (It will be installed in vendor/bin folder)
    class SampleTest extends TestCase{
        //function name must start with test
        //Must extends TestCase
        function testSomething(){
            $result = 2 + 2;
            $this->assertEquals(4, $result);
        }
    }

    //TestCase from Project's Source Code
    class Calculator{
        function add(...$operands){
            return array_sum($operands);
        }
        function subtract($a, $b){
            return $a - $b;
        }
    }

    //Now, in tests folder- CalculatorTest.php
    require("../src/Calculator.php"); //No Need if we configure composer autoload
    class CalculatorTest extends TestCase{
        private $calc;
        protected function setUp():void{
            $this->calc = new Calculator();
        }
        function testAdditionOfTwoNumbers(){
            $result = $this->calc->add(2, 3);
            $this->assertEquals(5, $result);
            //we can write multiple assertion here
        }
    }

//Configuring php unit using phpunit.xml (like color and others configuration in command line)

//Automatic Namespace Resolving and Autoload: Include autoload in composer.json in psr-4 format with namespaces and run: composer dump-autoload.

//In PHP, a DocBlock, also known as a "doc comment," is a special type of comment that provides documentation for classes, functions, methods, properties, and other code elements. DocBlocks are used to generate documentation using tools like PHPDoc. /** @ */ - syntax
//Multiple test in a single function using data provider
function dataProviderForMultiplication(){
    return [
        [1,2,3],
        [4,5,6]
    ];
}
/** @dataProvider dataProviderForMultiplication */
function testMultiplicationOfTwoNumbersUsingDataProvider($a, $b, $expected){
    $result = $this->calc->multiply($a, $b);
    $this->assertEquals($expected, $result);
}

//Name has not test, so can just add php docBlock annotation, then it will be automatically run as test case
        /** @test */
        function dos(){
            //...
        }

//TDD: Test Driven Development (Test First Code Then)
?>